env:
    node: true
    es2022: true
    jest: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-unused-vars:
        - disable
    no-implicit-coercion:
        - error
